export const documentationConfig = {
  title: 'Parseum Documentation',
  description:
    'Documentation for Parseum - A markdown to HTML parser and editor built using Peggy.js, React, TailwindCSS and DaisyUI.',
  siteUrl: 'https://vikiru.github.io',
  base: '/parseum',
  authorName: 'Visakan Kiribakaran',
  jobTitle: 'Software Engineer',
  portfolioWebsite: 'https://vikiru.vercel.app',
  githubAuthor: 'https://github.com/vikiru',
  linkedinProfile: 'https://linkedin.com/in/viskirubakaran',
  alumniUniversity: 'Carleton University',
  githubRepo: 'https://github.com/vikiru/parseum',
  liveDemoUrl: 'https://parseum.surge.sh',
  projectVersion: '1.0.0',
  projectStartDate: '2024-02-01',
  projectEndDate: '2024-03-31',
  programmingLanguage: 'JavaScript',
  keywords: ['markdown', 'html', 'parser', 'editor', 'peggy.js', 'react', 'tailwindcss', 'daisyui'],
  license: 'https://opensource.org/licenses/MIT',
  themeColor: '#3b82f6',
  logoFileName: 'logo.png',
  faviconFileName: 'favicon.ico',
};
